### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by Uzaaft** [Eik-Lab/vix_trigger#1]
- [x] Write requirements.txt 
- [x] Rewrite functions to handle the yfinance API 
- [ ] Tentativ: Rewrite to StreamLit

**Comment by Uzaaft** [comment]
Issue 3 will be fixed by PR #3
